### ISSUE TITLE
Document `$stickyState.reset()` (was: Can I programmatic closed a sticky state?)

### ISSUE THREAD

**Issue by kevfuzz** [christopherthielen/ui-router-extras#162]
Hi,

Enjoying using the sticky states addon!

Is there I way I can actually close a sticky state when I'm finally done with it and want it to be destroyed?

Regards,
Kev.

**Comment by christopherthielen** [comment]
`$stickyState.reset()` to clear all stickys or `$stickyState.reset('state')` to reset a specific one.

**Comment by leandroz** [comment]
I just see this and try the method $stickyState.reset(); and is giving me an error:

TypeError: Cannot read property 'name' of null
    at getInactivatedState (file:///android_asset/www/lib/ui-router-extras/release/ct-ui-router-extras.js:439:49)
    at Object.reset (file:///android_asset/www/lib/ui-router-extras/release/ct-ui-router-extras.js:631:25)
    at Object.$userService.logout (file:///android_asset/www/js/build.js:9287:17)
    at new logoutCtrl (file:///android_asset/www/js/build.js:2368:16)
    at invoke (file:///android_asset/www/lib/angular/angular.js:4182:17)
    at instantiate (file:///android_asset/www/lib/angular/angular.js:4190:27)
    at Object.$injector.instantiate (file:///android_asset/www/lib/ui-router-extras/release/ct-ui-router-extras.js:1548:22)
    at file:///android_asset/www/lib/angular/angular.js:8453:28
    at file:///android_asset/www/lib/angular-ui-router/release/angular-ui-router.js:3897:28
    at invokeLinkFn (file:///android_asset/www/lib/angular/angular.js:8217:9) <ui-view class="main-view ng-scope">

**Comment by pparsons** [comment]
I am getting the same error as @leandroz:
 
TypeError: Cannot read property 'name' of null
    at p (http://localhost:9000/bower_components/ui-router-extras/release/modular/ct-ui-router-extras.sticky.min.js:2:997)
    at Object.$get.$.reset (http://localhost:9000/bower_components/ui-router-extras/release/modular/ct-ui-router-extras.sticky.min.js:2:3396)
    at Scope.$scope.resetState (http://localhost:9000/scripts/controllers/termSearch.js:19:17)
    at $parseFunctionCall (http://localhost:9000/bower_components/angular/angular.js:12345:18)
    at chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:798:21
    at Scope.$get.Scope.$eval (http://localhost:9000/bower_components/angular/angular.js:14401:28)
    at Scope.$get.Scope.$apply (http://localhost:9000/bower_components/angular/angular.js:14500:23)
    at Scope.ng.config.$provide.decorator.$delegate.__proto__.$apply (<anonymous>:864:30)
    at Scope.scopePrototype.$apply (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1478:22)
    at HTMLButtonElement.<anonymous> (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:797:25)
  (anonymous function)

**Comment by rplute** [comment]
What about a programmatic enable? Thanks.

**Comment by JetFault** [comment]
+1 Getting the same error as @leandroz and @pparsons. Did yall find a solution?

**Comment by marcelocelo** [comment]
+1 Getting the same error as @JetFault. 
I have nested abstract states and the parent state is sticky. I need to complete a registration and clean the sticky state. I tried the reset without state name and with state name. In none of them was able to do a reset. Try rest with all states in path from current state. Nothing.

**Comment by ashishnextit** [comment]
Hi,

I want to reset the current state....... I found that the $stickyState.reset('state1') works fine only when the 'state1' is inactive........... I made the current state inactive by using $stickyState.stateInactivated($state.$current) and then called $stickyState.reset('state') but the DOM did not destroy. After going to another state named 'state2' the DOM was cleared. In this consequence I again tried to go 'state1' but the template did not appear and the controller did not invoked.......

**Comment by pparsons** [comment]
Has anyone managed to solve this problem? I am having the same issue as @ashishnextit 

If you look at the reset function in ui-router-extras.sticky.js you see that it is actually expecting an inactive state as a parameter. If the state is not inactive, the function will return false. I tried to set the current state as inactive, but I am having the same problem as @ashishnextit

**Comment by manuelfc1** [comment]
+1 $stickyState.reset() not working at all for me with and without state name. Even when I use ui-sref-opt ="{reload:true}" in the parent state transitioning to the substate, it does not reset the substate.

**Comment by christopherthielen** [comment]
Sorry all, I said .reset() takes no parameters to reset all states, that was incorrect.  In 0.0.14 you can use `$stickyState.reset("*")` to reset all inactive states.  Also added docs to the docs page (but haven't pushed the docs update to github yet)

**Comment by christopherthielen** [comment]
@ashishnextit 
> I found that the $stickyState.reset('state1') works fine only when the 'state1' is inactive.......

Yes, because if you reset the currently active state, then what state are you on?  You cannot `$stickyState.reset()` the active state.
