### ISSUE TITLE
Angular 1.6.5 Cannot read property '$$equals' of undefined

### ISSUE THREAD

**Issue by nmainardi** [christopherthielen/ui-router-extras#374]
I've just installed ui-router-extras with npm in my angular project but it doesn't work. 
The console error is:
`TypeError: Cannot read property '$$equals' of undefined
    at paramsEqualForState (https://localhost:8443/qiss/node_modules/ui-router-extras/release/ct-ui-router-extras.js:473:29)
    at calcTreeChanges (https://localhost:8443/qiss/node_modules/ui-router-extras/release/ct-ui-router-extras.js:506:53)
    at Object.processTransition (https://localhost:8443/qiss/node_modules/ui-router-extras/release/ct-ui-router-extras.js:542:29)
    at e.$state.transitionTo (https://localhost:8443/qiss/node_modules/ui-router-extras/release/ct-ui-router-extras.js:1082:48)
    at t.r [as handler] (https://localhost:8443/qiss/node_modules/angular-ui-router/release/angular-ui-router.min.js:13:1854)
    at t.sync (https://localhost:8443/qiss/node_modules/angular-ui-router/release/angular-ui-router.min.js:13:3983)
    at https://localhost:8443/qiss/node_modules/angular-ui-router/release/angular-ui-router.min.js:13:4147
    at https://localhost:8443/qiss/node_modules/angular-ui-router/release/angular-ui-router.min.js:14:3269
    at Array.forEach (native)
    at https://localhost:8443/qiss/node_modules/angular-ui-router/release/angular-ui-router.min.js:14:3242`

My versions:
    "angular": "^1.6.5",
    "angular-ui-router": "^1.0.3"

and ui-router-extras 0.1.3

If I change version of angular-ui-router to 0.2.15 (like i saw in demo) I get this error:
`Error: transition superseded
    at $StateProvider.$get (angular-ui-router.js:2866)
    at Object.invoke (angular.js:5040)
    at $StateProvider.origProvider.$get (angular.js:4906)
    at Object.invoke (angular.js:5040)
    at $StateProvider.origProvider.$get (angular.js:4906)
    at Object.invoke (angular.js:5040)
    at $StateProvider.origProvider.$get (angular.js:4906)
    at Object.invoke (angular.js:5040)
    at angular.js:4832
    at getService (angular.js:4981) "Possibly unhandled rejection: {}"`

So, what is the correct combination of versions for angular 1.6.5?

**Comment by ShrinathGupta** [comment]
Even I have the same issue having same library references, the issue is because of ownParams property which is not present inside state Object. 
(state.ownParams) ownParams is not defined.
Still digging into it.
@christopherthielen Any help will be appreciated.

**Comment by ghost** [comment]
This happened with angular 1.5.10 and 1.6.6. I think it may happen with other versions as well.

Any update guys ?

**Comment by patrickPDD** [comment]
Has this been resolved anywhere?

**Comment by ghost** [comment]
What I did was install an older angular-ui-router

        "angular": "^1.7.5",
        "angular-animate": "^1.7.5",
        "angular-aria": "^1.7.5",
        "angular-material": "^1.1.10",
        "angular-material-data-table": "^0.10.10",
        "angular-messages": "^1.7.5",
        "angular-recaptcha": "^4.2.0",
        "angular-sanitize": "^1.7.5",
        "angular-translate": "^2.18.1",
        "angular-ui-router": "^0.4.2",
